### ISSUE TITLE
clang support

### ISSUE THREAD

**Issue by jungle-boogie** [tonyfischetti/qstats#3]
Hello,

Just in case you were not aware, you utility will compile with clang, you just have to specify the CC.
`make CC=clang`

Is it possible to have to auto detect the CC?

Thanks!

**Comment by kirbyfan64** [comment]
Let me guess: you're using OSX, right?

**Comment by jungle-boogie** [comment]
> Let me guess: you're using OSX, right?

No, freebsd:

    % cc -v
    FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
    Target: x86_64-unknown-freebsd10.2
    Thread model: posix
    Selected GCC installation:

**Comment by tonyfischetti** [comment]
Why would it compile with clang? I set the CC to gcc in src/Makefile.

I tried not to use configure scripts/autotools that would have done that because I thought it was over kill. Isn't CC an environment variable?

**Comment by kirbyfan64** [comment]
Well, I *think* you could do something like this in the Makefile:

```make
CC := $(firstword
    $(CC)
    $(shell which cc)
    $(shell which gcc)
    $(shell which clang)
    $(shell which icc))
ifeq ($(CC),)
    $(error Cannot detect C compiler)
endif
```

@tonyfischetti Because FreeBSD doesn't have GCC anymore...

**Comment by tonyfischetti** [comment]
Ohhh! I misunderstood the original comment! Yeah, I just left it up the the user to specify their compiler of choice but I'll try the fix that @kirbyfan64 provided.

I don't blame FreeBSD, not just for the licensing, but all my c projects so far run faster if compiled on clang although -03 closes the gap. I'm still married to the gcc/gdb stack, though :/

**Comment by kirbyfan64** [comment]
Well, Clang works perfectly with recent gdb versions (though if you want the *ultimate* performance, Intel is hard to beat).
