### ISSUE TITLE
Use getline instead of fgets

### ISSUE THREAD

**Issue by tonyfischetti** [tonyfischetti/qstats#4]
So there is no maximum line length

**Comment by kirbyfan64** [comment]
Isn't `getline` a GNU extension, though? It's definitely possible to read a full line with `fgets` (though I wouldn't call the result elegant by any means!).

**Comment by tonyfischetti** [comment]
`getline` is actually a POSIX standard. For example, on my Mac, if you type `man 3 getline` I see that it's from BSD's libc since FreeBSD 8

**Comment by kirbyfan64** [comment]
Ah, right; they're Posix since 2008. My bad!

**Comment by tonyfischetti** [comment]
Eh, its fine
